Calculator calc = new Calculator();
decimal add1 = calc.dynamicCalculationMethod(10, 67.5, 'ADDITION');
system.debug('Output --> ' + add1);

Decimal subt1 = calc.dynamicCalculationMethod(90, 60, 'SUBTRACTION');
system.debug('Output --> ' + subt1);

Decimal div1 = calc.dynamicCalculationMethod(8, 2, 'DIVISION');
system.debug('Output --> ' + div1);

Decimal mul1 = calc.dynamicCalculationMethod(6, 4, 'MULTIPLICATION');
system.debug('Output --> ' + mul1);

